### ISSUE TITLE
Service Request - zip entire directory

### ISSUE THREAD

**Issue by benedictbasa** [Permafrost/Tundra#126]
It is quite common to compress entire folder in zip or tar.gz format.

It would be good if there is a way to have this option

tundra.directory:zip -> to zip entire directory
tundra.directory:gzip -> to have a tar option to tar entire directory and gzip

I think some ideas here is good to use apache commons compress

https://stackoverflow.com/questions/7128171/how-to-compress-decompress-tar-gz-files-in-java

**Comment by lachlan** [comment]
I just committed https://github.com/Permafrost/Tundra/commit/aa1f04372a58894336a9d649e0e246682f9832dd which adds the service `tundra.directory:zip` for compressing files in a given directory into a zip archive.

**Comment by benedictbasa** [comment]
Thanks alot would this be part of the next release?
