### ISSUE TITLE
[question] Can Tundra be compiled on JVM 1.5?

### ISSUE THREAD

**Issue by gvlx** [Permafrost/Tundra#55]
1.5.0_15 (49.0) is the base JVM version on 7.1.3.

I know it is old, but in some cases I'm stuck with this.

Is the code compatible with this version?

Thank You.

**Comment by lachlan** [comment]
@gvlx do you have any update on this request - did you try recompiling for 1.5 - how did you get on?

**Comment by gvlx** [comment]
@lachlan Tundra code makes references to Queue structures which only appear on JVM 1.6.
Adapting code to still work on JVM 1.5 would be substantial and would yield very small returns.

Given current status of update and security of JVM 1.5 and 1.6, I don't see the point any longer in proceeding with this change.
